routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main.index1');
});
Route::get('/mapa', function(){
    $config = array();
    $config['center'] = 'New York, USA';
    GMaps::initialize($config);
    $map = GMaps::create_map();

    echo $map['js'];
    echo $map['html'];
});
Route::resource('/contrato', 'ContratoController');
Route::get('/packs', 'ContratoController@getPaquetes');
Route::get('/name/{name}', 'ContratoController@nameExist');
Route::get('/busqueda', 'ContratoController@busqueda');



Route::resource('/servicios', 'ServiciosController');
Route::get('/name/{name}', 'ServiciosController@nameExist');


Route::resource('/cita', 'CitaController');



Route::resource('/reportes','ContratoController@reportes');


Route::get('reportes',  function (){
	return view('contratos.reportes');
});




Route::resource('/agendar', 'AgendarSerController');



Route::get('reporte',  function (){
	return view('servicios.reporte');
});

Route::get('buscar', function(){
	return view('servicios.buscar');
});






Route::resource('/servicios', 'ServiciosController');

Route::resource('/Instaladores', 'InstaladoresController');

app/Http/Controllers/InstaladoresController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Instalador;


class InstaladoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Instaladores = Instalador::orderBy ( 'id' , 'DESC' )->paginate ( 3 );

       return view( 'Instaladores.index' ,compact ( 'Instaladores' ));
    }

    /**3
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Instaladores.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,(['nombre'=>'required','telefono'=>'required']));
        main::create($request->all());
        return redirect()->route('Instaladores.index')->with('Registro exitoso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Instaladores=instalador::find($id);
        return view('Instaladores.show', compact('Instaladores'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Instaladores=instalador::find($id);
        return view('Instaladores.show', compact('Instaladores'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[ 'folio'=>'required', 'nombre'=>'required', 'apellido'=>'required', 'telefono'=>'required']);

        instalador::find($id)->update($request->all());
        return redirect()->route('Instaladores.index')->with('Registro actualizado satisfactoriamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        instalador::find($id)->delete();
        return redirect()->route('Instaladores.index')->with('Registro eliminado satisfactoriamente');
    }
}

resources/views/Instaladores/create.blade.php
@extends('main.app', ['titulo' => 'Instaladores'])


@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif
 
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Nuevo Instalador</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('Instaladores.store') }}"  role="form">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="folio" id="folio" class="form-control input-sm" placeholder="folio">
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" placeholder="Nombre de instalador">
									</div>
								</div>
							</div>
 
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="apellido" id="apellido" class="form-control input-sm" placeholder="apellifo">
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="telefono" id="telefono" class="form-control input-sm" placeholder="telefono">
									</div>
								</div>
							</div>
							
							<div class="row">
 
								<div class="col-xs-12 col-sm-12 col-md-12">
									<input type="submit"  value="Guardar" class="btn btn-success btn-block">
									<a href="{{ route('Instaladores.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	
 
							</div>
						</form>
					</div>
				</div>
 
			</div>
		</div>
	</section>
	@endsection

resources/views/Instaladores/edit.blade.php
@extends('layouts.layout')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif
 
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Nuevo Libro</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('Instaladores.update',$libro->id) }}"  role="form">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="folio" id="folio" class="form-control input-sm" value="{{$instalador->folio}}">
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" value="{{$instalador->nombre}}">
									</div>
								</div>
							</div>
 
							<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="apellido" id="apellido" class="form-control input-sm" value="{{$instalador->apellido}}">
									</div>
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="telefono" id="telefono" class="form-control input-sm" value="{{$instalador->telefono}}">
									</div>
								</div>
							</div>
							
							<div class="row">
 
								<div class="col-xs-12 col-sm-12 col-md-12">
									<input type="submit"  value="Actualizar" class="btn btn-success btn-block">
									<a href="{{ route('Instaladores.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	
 
							</div>
						</form>
					</div>
				</div>
 
			</div>
		</div>
	</section>
	@endsection

resources/views/Instaladores/index.blade.php
@extends('main.app', ['titulo' => 'Instaladores'])

@section('content')
<div class="row">
  <section class="content">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-body">
        
          <div class="pull-right">
            <div class="btn-group">
              <a href="{{ route('Instaladores.create') }}" class="btn btn-info" >Registrar</a>
            </div>
          </div>
          <div class="table-container">
            <table id="mytable" class="table table-bordred table-striped">
             <thead>
               <th>FOLIO</th>
               <th>NOMBRE</th>
               <th>APELLIDO</th>
               <th>TELEFONO</th>
               <th>Editar</th>
               <th>Eliminar</th>
             </thead>
             <tbody>
              @if($Instaladores->count())  
              @foreach($Instaladores as $ins)
              {{$ins}}
              <tr>
                <td>{{$instalador->folio}}</td>
                <td>{{$instalador->nombre}}</td>
                <td>{{$instalador->apellido}}</td>
                <td>{{$instalador->telefono}}</td>
                
                <td><a class="btn btn-primary btn-xs" href="{{action('InstaladoresController@edit', $instalador->id)}}" ><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td>
                  <form action="{{action('InstaladoresController@destroy', $instalador->id)}}" method="post">
                   {{csrf_field()}}
                   <input name="_method" type="hidden" value="DELETE">
 
                   <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span></button>
                 </td>
               </tr>
               @endforeach 
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
            </tbody>
 
          </table>
        </div>
      </div>

      {{ $Instaladores->links() }}
    </div>
  </div>
</section>
 
@endsection